version: '3.7'

services:

  web-application:
    image: merisaarinenwebimage.azurecr.io/web-application:latest
    pull_policy: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true