# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - merisaarinen-portfolio

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://merisaarinenwebimage.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d8087f6e6883452ab34a3601a349cfa9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8439115932fe423ab60fafbab6a882dd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: merisaarinenwebimage.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d8087f6e6883452ab34a3601a349cfa9 }}/web-application-release:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'merisaarinen-portfolio'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d25348b9b34458f921bfebad744dcf5 }}
        images: 'merisaarinenwebimage.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d8087f6e6883452ab34a3601a349cfa9 }}/web-application-release:${{ github.sha }}'